# Alacritty Config
#
# See: https://github.com/alacritty/alacritty#configuration
# See: https://github.com/alacritty/alacritty/blob/master/alacritty.yml
# See: https://defkey.com/alacritty-0-9-shortcuts

[colors.primary]
background = "0x1d1f21"
foreground = "0xe6edf3"

[env]
TERM = "xterm-256color"

# Font {{{

[font.bold]
family = "Fira Code"
style = "SemiBold"

[font.bold_italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"

# }}}

# Window {{{

[window.padding]
x = 5
y = 5

# }}}

# Keyboard {{{

# <3
[[keyboard.bindings]]
chars = "€"
key = "Key2"
mods = "Alt"

# }}}

# Shell {{{

# You can set `shell.program` to the path of your favorite shell, e.g.
# `/bin/fish`. Entries in `shell.args` are passed unmodified as arguments to the
# shell.
#
# Default:
#   - (macOS) /bin/bash --login
#   - (Linux/BSD) user login shell
#   - (Windows) powershell
#
# Start tmux https://pawelgrzybek.com/autostart-tmux-on-alacritty-launch/

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

# }}}
