# Alacritty Config
#
# See: https://github.com/alacritty/alacritty#configuration
# See: https://github.com/alacritty/alacritty/blob/master/alacritty.yml
# See: https://defkey.com/alacritty-0-9-shortcuts
# See: https://arslan.io/2018/02/05/gpu-accelerated-terminal-alacritty/

env:
  TERM: xterm-256color

hide_when_typing: true

font:
  normal:
    family: &codefont "FiraCode Nerd Font"
  bold:
    family: *codefont
    style: SemiBold
  bold_italic:
    family: *codefont
    style: Italic

colors:
  primary:
    background: '0x152528'

window:
  # startup_mode: Fullscreen
  padding:
    x: 0
    y: 0

key_bindings:
  # <3
  - { key: Key2, mods: Alt, chars: '€' }

shell:
  # Start tmux https://pawelgrzybek.com/autostart-tmux-on-alacritty-launch/
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"
