# This is for Windows machine running WSL. This must be installed by
# hand in %APPDATA%\alacritty\alacritty.toml.

# Start tmux https://pawelgrzybek.com/autostart-tmux-on-alacritty-launch/
[terminal]
shell.program = 'C:\Program Files\WSL\wsl.exe'
shell.args = ["--cd ~", "--exec /bin/zsh -l -c", "tmux attach || tmux"]

[mouse]
hide_when_typing = true

[colors.primary]
background = "0x1a1b26"
foreground = "0xe6edf3"

[font]
size = 10.0

[font.bold]
family = "Fira Code"
style = "SemiBold"

[font.bold_italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"

[[keyboard.bindings]]
chars = "€"
key = "Key2"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "G"
mods = "Super"

[window]
startup_mode = "Fullscreen"

[window.padding]
x = 5
y = 5
