#!/usr/bin/env zsh
#  _____                               _       _
# |_   _|                             (_)     | |
#   | |_   _ _ __   ___  ___  ___ _ __ _ _ __ | |_
#   | | | | | '_ \ / _ \/ __|/ __| '__| | '_ \| __|
#   | | |_| | |_) |  __/\__ \ (__| |  | | |_) | |_
#   \_/\__, | .__/ \___||___/\___|_|  |_| .__/ \__|
#       __/ | |                         | |
#      |___/|_|                         |_|
#
# Generate barrel file for the current folder. /Not/ recursive.

function barrel {
  local INDEX='index.ts'

  rg --files -g '*.ts' -g '*.tsx' -g "!${INDEX}" -g '!*.spec.ts' --max-depth 1 \
    | sort \
    | sed -e "s,^,export * from './," \
    | sed -E -e "s,\.(ts|tsx)$,'\;," \
    > $INDEX
}
