#!/usr/bin/env zsh
#  _____                               _       _
# |_   _|                             (_)     | |
#   | |_   _ _ __   ___  ___  ___ _ __ _ _ __ | |_
#   | | | | | '_ \ / _ \/ __|/ __| '__| | '_ \| __|
#   | | |_| | |_) |  __/\__ \ (__| |  | | |_) | |_
#   \_/\__, | .__/ \___||___/\___|_|  |_| .__/ \__|
#       __/ | |                         | |
#      |___/|_|                         |_|
#
# Generate barrel for components classes under the current folder.

function compbarrel {
  local INDEX='index.ts'

  rg --files -g '*.component.ts'  \
    | sort \
    | sed -e "s,^,export * from './,;s,\.ts$,'\;," \
    > $INDEX
}
