#!/usr/bin/env zsh
#  _____                               _       _
# |_   _|                             (_)     | |
#   | |_   _ _ __   ___  ___  ___ _ __ _ _ __ | |_
#   | | | | | '_ \ / _ \/ __|/ __| '__| | '_ \| __|
#   | | |_| | |_) |  __/\__ \ (__| |  | | |_) | |_
#   \_/\__, | .__/ \___||___/\___|_|  |_| .__/ \__|
#       __/ | |                         | |
#      |___/|_|                         |_|
#
# Recursive simple rename of FOO with BAR

function fixxor {
	local TERM=$1
	local REPLACEMENT=$2

	sed -i '' -e "s,${TERM},${REPLACEMENT},g" $(rg "${TERM}" -l)
}
