#!/usr/bin/env zsh
#   __ _            _____
#  / _(_)          |  _  |
# | |_ ___  ____  _| |/' |_ __
# |  _| \ \/ /\ \/ /  /| | '__|
# | | | |>  <  >  <\ |_/ / |
# |_| |_/_/\_\/_/\_\\___/|_|
#
# Simple rename of FOO with BAR using ripgrep.

function fixxor {
  local search=$1
  local replace=$2
  local found_files=$(rg "${search}" -l)

  if [[ $#found_files == 0 ]]; then
    echo "fixxor: term not found in any files: ${search}"
    return 1
  fi

  if [[ $OSTYPE =~ 'darwin' ]]; then
    export alias sed=gsed
  fi

  echo $found_files | xargs -P 4 -n 10 sed -i '' -e "s,${search},${replace},g"
}
