#!/usr/bin/env zsh
#  _____          _
# |  __ \        | |
# | |__) |__ _ __| |
# |  ___/ _ \ '__| |
# | |  |  __/ |  | |
# |_|   \___|_|  |_|
#
# Redact sensitive tokens and passwords in passed input.
# See: https://regex101.com/r/0axM8q/1

function redact {
  while read -r DATA; do
    echo $DATA | perl -pe 's/(((?<=secret)|(?<=password)).*?(\t|\s|=))(.*)/$1$2*****/'
  done
}
