#!/usr/bin/env zsh
# ______            _
# | ___ \          | |
# | |_/ /   _ _ __ | | ___   __ _
# |    / | | | '_ \| |/ _ \ / _` |
# | |\ \ |_| | | | | | (_) | (_| |
# \_| \_\__,_|_| |_|_|\___/ \__, |
#                            __/ |
#                           |___/
#
# Edit weekly running log in vim. Functions should be obvious from name. Feel
# free to fork and dork.

LOG=$(cat <<EOF
**Monday (CHANGEME):**

- <strava_link>

**Tuesday (CHANGEME):**

- <strava_link>

**Wednesday (CHANGEME):**

- <strava_link>

**Thursday (CHANGEME):**

- <strava_link>

**Friday (CHANGEME):**

- <strava_link>

**Saturday (CHANGEME):**

- <strava_link>

**Sunday (CHANGEME):**

- <strava_link>

EOF
)

echo $LOG | nvim -c 'set filetype=markdown' -
