" Core Configuration {{{

" Enable syntax highlighting
syntax on

" Backspace will delete
set backspace=indent,eol,start

" Enable relative line numbers
set nu relativenumber

" Open split below and to the right instead of up and to the left
set splitbelow splitright

" Force order of line endings
set ffs=unix,dos

" Follow auto indent
set autoindent

" Don't wrap lines outside of words
set nowrap breakindent linebreak nolist

" Enable ruler for column count
set ruler

" Enable statusbar
set laststatus=2

" Accept instructions from the top n lines of a file
set modelines=1

" Stop annoying problem on OS X
" Arrow keybinds cause a status popup to appear when I tab back to vim
set shortmess=a

" Disable visual bell. It's annoying as crap in git bash on Windows
set visualbell t_vb=

" More informative statusbar
" TODO(mark 2021-12-29): document this and expand
set statusline=\ %<%f\ %h%m%r\ %y%=%{v:register}\ %-14.(%l,%c%V%)\ %P

" }}}

" Scrolling! {{{

" Set padding when scrolling
set scrolloff=10 sidescrolloff=10

" Increase scroll speed
set ttyfast

" Change how buffer is redrawn. /Should/ increase scroll speed
" TODO(mark 2021-12-31): does this affect weird syntax highlighting in big
" Angular files?
" set lazyredraw

" }}}

" Completion and Indentation {{{

" Ignore common temp files and directories
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.cache,*.bak,*.pyc,*.class
set wildignore+=node_modules
set wildignore+=*public/packs*

" Menu display output
set wildmenu wildmode=list:full

" Search as I type, and highlight results
set incsearch smartcase hlsearch

" Searches are assumed to be global on a line
set gdefault

" Set tabbing and indentation
set tabstop=2 softtabstop=2 shiftwidth=2
set expandtab smartindent

" }}}

" Saving, Filesystem and History {{{

" Write file when it loses focus
set autowrite

" More frequent saves and bigger undo history
set updatecount=50 history=2000 undolevels=2000

" Keep a persistent backup file
set undofile undodir=.undo,~/tmp,/tmp

" Disable swap files, but set directories in case they *are* turned on
set noswapfile directory=~/.vim/.tmp,~/tmp,/tmp

" Highlight the current line and set the colour
set cul

" }}}

" netrw! {{{

" Set gx open command for macOS
" FIXME(mark 2021-12-18): improve this, it does not at all work
if has('macunix')
  let g:netrw_browsex_viewer = 'open'
endif

" }}}

" Plugins {{{

runtime plugin/plug.vim

" }}}
