#!/bin/sh
#  _____ _ _
# |  __ (_) |
# | |  \/_| |_
# | | __| | __|
# | |_\ \ | |_
#  \____/_|\__|
#
# Append - if found - the ticket number from the current branch to the start of
# the git commit message.

COMMIT_MSG_FILE=$1
BRANCH=$(git symbolic-ref --short HEAD | tr '[:lower:]' '[:upper:]')
TICKET=$(grep -Eio '^[A-Za-z]+-[0-9]+' <<< $BRANCH)

function ticket_not_in_commit {
  local COMMIT=$1
  local TICKET=$2

  [[ -n $TICKET ]] && [[ ! $(head -n 1 $COMMIT) =~ $TICKET ]]
}

if ticket_not_in_commit $COMMIT_MSG_FILE $TICKET; then
  echo $TICKET >> $COMMIT_MSG_FILE
fi
